In [1]:
import numpy as np

In [50]:
# Creating numpy arrays from lists
a=[10,20,30,40]
b=np.array(a)
print(b)
c=np.array([100,200,300,400])
print(c)

[10 20 30 40]
[100 200 300 400]


In [22]:
# numpy data upcasting from int to float
a = np.array([12,3.5,6,10.12])
print(a)

[12.    3.5   6.   10.12]


In [26]:
# Specifying datatype while creating
a=np.array([12,34,56,68], dtype='int8')
b=np.array([12,34,56,68], dtype=np.float32)
print(a,b)
c=[[12,34,56],[12,34,56]]
d=np.array(c)
print(d)

[12 34 56 68] [12. 34. 56. 68.]
[[12 34 56]
 [12 34 56]]


In [32]:
# Creating numpy arrays from scratch
# zeros, ones, eye, full, empty,arange, linspace, random, randint
a=np.zeros(10)
# print(a)
b = np.zeros((3,4))
# print(b)
c=np.zeros((3,2,3))
# print(c)
d=np.ones((3,4,2,2), dtype=np.int32)
# print(d)
e=np.eye(5, dtype=np.int16) # identity matrix
# print(e)
f=np.full((3,2,5), 103857) # for filling a matrix with specififed value
# print(f)
g = np.empty((10,5))
# print(g)
a=np.arange(2,100,3)  # arange(start, stop, step)
# print(a)
b= np.linspace(0,12,5) #linspace(start, stop, no of values)
# print(b)
# print(np.random.random((3,2))) # picks one random number from uniform distribution
print(np.random.randint(100, size=(2,3,4)))

[[[91 61 68 15]
  [60 98 32 19]
  [51  8 82 32]]

 [[38 71 73 51]
  [90 19 71 32]
  [47 56 72  0]]]


In [34]:
# numpy attributes
# creating arrays with size
x1 = np.random.randint(100, size=(8))
# print(x1)
x2 = np.random.randint(100, size=(3,4))
# print(x2)
x3 = np.random.randint(100, size=(2,3,4))
# print(x3)
print(x3.size) # size will give numer of elements
print(x2.shape) # shape of the matrix
print(x2.ndim)  # number of dimensions
print(x2.dtype)  # datatype
print(x2.itemsize)  # memory for each element
print(x2.nbytes)  # total memory occupied
# ndim, shape, size, dtype, itemsize, nbytes

24
(3, 4)
2
int64
8
96


In [45]:
# Indexing - Accessing and modifying the contents
# single dimensional, multi-dimensional arrays
# print(x1)
# print(x1[-2]) # +ve index as well as -ve index
# print(x2)
# print(x2[1,2]) # 1st index - rows, 2nd index - columns
print(x3)
print(x3[0,2,3])
x3[0,2,3] = 100
print(x3)

[[[90 90 30 27]
  [42 98 55 26]
  [ 3 13 13 58]]

 [[50 89 66 14]
  [17 24 34 23]
  [11 71 23 95]]]
58
[[[ 90  90  30  27]
  [ 42  98  55  26]
  [  3  13  13 100]]

 [[ 50  89  66  14]
  [ 17  24  34  23]
  [ 11  71  23  95]]]


In [58]:
# Slicing - Accessing sub arrays
# x[start:stop:step]
# print(x1)
# print(x1[2:6:2])
# print(x1[:4])
# print(x1[2:])
# print(x1[:])
# Single and multi dimensional arrays
# Accessing complete rows and columns
# print(x2)
# print(x2[:2, 1:3])
# print(x2[:, 1:])
x4 = x2[:, 1:]
print(x4)

[[89 76 49]
 [ 8 82 33]
 [63 71 51]]


In [65]:
# Copying the arrays from one another, copying subarrays
print(x2)
# x4 = x2[1:3, 2:].copy()
x4=x2.copy()
print(id(x4))
x5=x2
print(id(x5), id(x2))
print(x5)

[[58 89 76 49]
 [77  8 82 33]
 [79 63 71 51]]
139988085553472
139988112230320 139988112230320
[[58 89 76 49]
 [77  8 82 33]
 [79 63 71 51]]


In [76]:
# Reshaping of arrays
print(x2)
print(x2.shape)
x5=x2.reshape(x2.size)  # to get the number of elements automatically.
print(x5.shape)
print(x5)
print(x2.reshape(1,12))  # number of elements should match.
# newaxis - Increasing the axis

[[58 89 76 49]
 [77  8 82 33]
 [79 63 71 51]]
(3, 4)
(12,)
[58 89 76 49 77  8 82 33 79 63 71 51]
[[58 89 76 49 77  8 82 33 79 63 71 51]]


In [33]:
# Array concatenation and splitting
# Single and multi dimensional arrays
# axis option
# hstack, vstack
# split, hsplit, vsplit
# x1 = np.random.randint(100, size=(3,3))
# x2 = np.random.randint(100, size=(3,3))
# x3 = np.random.randint(100, size=(3,3))
# x4 = np.random.randint(100, size=(3,3))
# print(x1,x2)
# print(np.hstack([x2,x1,x3,x4]))
# print(np.vstack([x2,x1,x3,x4]))
# c = np.concatenate([x1,x2])
# print(c)
x1 = np.random.randint(100, size=(6,6))
print(x1)
print(np.vsplit(x1, [3]))

[[99 61  1 14 62 97]
 [27 31 61 71 94 28]
 [90 83 63  8 80 70]
 [23 48 42 25  7 51]
 [57 69 81 92 36 70]
 [44 19 30 53 72  3]]
[array([[99, 61,  1, 14, 62, 97],
       [27, 31, 61, 71, 94, 28],
       [90, 83, 63,  8, 80, 70]]), array([[23, 48, 42, 25,  7, 51],
       [57, 69, 81, 92, 36, 70],
       [44, 19, 30, 53, 72,  3]])]


In [25]:
# Numpy vectorized operations through functions
# for loop example
a=[10,20,30,40,50]
# add 100 to all the elements
b=[]
for x in a:
    b.append(x+100)
print(b)

[110, 120, 130, 140, 150]


In [48]:
# Array arithmetic
# arithmetic operations with scalars
# a=np.random.randint(100, size=(5))
# print(a)
# print(a+100)
# print(a-100)
# print(a*100)
# print(a/100)
# print(a//100)
# print(a**100)
# print(a%100)
# print(100**a)

#arithmetic operations with two or more arrays
a=np.random.randint(100, size=(3,3))
b=np.random.randint(100, size=(3,3))
print(a,b)
# print(a+b)
a=a+b
c=np.empty((3,3))
np.add(a,b, out=c)
print(c)
# print(a**b)
# print(-a)
# a=np.array([0, 30, 45, 60, 90])
# print(a)
# print(np.arcsin(a))

[[41 75 62]
 [60 97 56]
 [80 95 83]] [[29 94 81]
 [ 3 22 32]
 [26 29 10]]
[[ 99. 263. 224.]
 [ 66. 141. 120.]
 [132. 153. 103.]]


In [16]:
# Aggregate functions - it gives one value
# reduce() on add, multiply
x1 = np.random.randint(20, size=(10))
print(x1)
# print(np.add(x1, 20))   # x1+20
# sum = np.add(x1,20)  # Total sum of all the elements, 
#axis=0 - along rows, axis=1 - along columns
# print(sum)
print(np.multiply.accumulate(x1))

# accumulate() on add, multiply
# outer() on multiply

[17 14 12  8 15 13 15  4  1  3]
[       17       238      2856     22848    342720   4455360  66830400
 267321600 267321600 801964800]


In [41]:
# Aggregate functions
# sum(), min(), max()
x1 = np.random.randint(100, size=(3,4,3))
print(x1)
# print(x1.max(axis=1))
# print(x1.argmax(axis=1)) # gives the index of min/max value
# multi-dimensional arrays with axis
x2 = x1.reshape(1,36)[0]
print(x2)
x3=x1.flatten()  # converts any matrix into one dimensional
print(x3)

[[[27 79 28]
  [12 35  0]
  [57 89 75]
  [ 8 43 85]]

 [[98  3 62]
  [64 13 90]
  [47 89 12]
  [65 47 54]]

 [[34  5 49]
  [56 95 67]
  [32 62  4]
  [47 49 21]]]
[27 79 28 12 35  0 57 89 75  8 43 85 98  3 62 64 13 90 47 89 12 65 47 54
 34  5 49 56 95 67 32 62  4 47 49 21]
[27 79 28 12 35  0 57 89 75  8 43 85 98  3 62 64 13 90 47 89 12 65 47 54
 34  5 49 56 95 67 32 62  4 47 49 21]


In [44]:
# Broadcasting - increasing the dimension of one of the operands according to the second operand
# Dimension will be changed to match the highest dimension available.
x1 = np.random.randint(100, size=(10))
print(x1)
print(x1+5)

[10 10 79 45 85  1 56 92 84 12]
[15 15 84 50 90  6 61 97 89 17]


In [20]:
# Comparison operators
# Comparing with scalar
# <,>,<=,>=,==,!=
x1 = np.random.randint(100, size=(3,4))
x2 = np.random.randint(100, size=(3,4))
print(x1,x2)
print(x1>10)
# print(x2[x1>10])  # masking, filtering the elements based on condition
# np.any(), np.all(), np.add.reduce(), np.multiply.reduce(), accumulate()
print(np.any(x1>10))

[[60 91  7  1]
 [95 54 74 97]
 [78 89 77 73]] [[21 62  5 36]
 [37 15 86 14]
 [79 31  0 22]]
[[ True  True False False]
 [ True  True  True  True]
 [ True  True  True  True]]
True


In [34]:
# Fancy indexing - creating index arrays, modifying values using fancy indexing
x = np.random.randint(10, size=(8))
print(x)
i = np.array([[1,3],[5,7]])
# x[i]=100  # the output shape depends on the index array shape
print(x[i])

[2 3 3 6 8 3 0 8]
[[3 6]
 [3 8]]


In [20]:
# numpy sorting - sort(), argsort(), sorting along rows and columns
x = np.random.randint(20, size=(8,8))
print(x)
# print(np.sort(x)[::-1])  # by default, it sorts row wise.
# print(np.argsort(x)[::-1]) # indexes of sorted array
# partition(), partition along axis
# to get the specified number of elements smallest elements at the beginning.
print(np.sort(x))
print(np.partition(x,3, axis=1))  getting smallest sub arrays

[[ 4 17 15 12  6 19  3 15]
 [ 9  4  7 11 19 13  7  5]
 [18  6 15  8 17 10 17 14]
 [13 14 16  6 16  2  6  2]
 [ 3  9  7 11 10  7 13  4]
 [ 8  1 10 15 17 18 15  5]
 [14 12 17 13  6 18 18 10]
 [12  2  5 15  7  2  0  2]]
[[ 3  4  6 12 15 15 17 19]
 [ 4  5  7  7  9 11 13 19]
 [ 6  8 10 14 15 17 17 18]
 [ 2  2  6  6 13 14 16 16]
 [ 3  4  7  7  9 10 11 13]
 [ 1  5  8 10 15 15 17 18]
 [ 6 10 12 13 14 17 18 18]
 [ 0  2  2  2  5  7 12 15]]
[[ 6  4  3 12 17 19 15 15]
 [ 4  5  7  7  9 13 19 11]
 [ 6  8 10 14 17 15 17 18]
 [ 2  2  6  6 16 14 16 13]
 [ 3  4  7  7  9 10 13 11]
 [ 1  5  8 10 15 15 17 18]
 [12 10  6 13 17 18 18 14]
 [ 2  0  2  2  5  7 12 15]]


In [12]:
a=[10,20,30,40,50,60]
x= np.array(a)
print(x)
# aggregation names
print(np.mean(x))
print(np.median(x))
print(np.std(x))
print(np.var(x))
# print(a[::-1])

[10 20 30 40 50 60]
35.0
35.0
17.07825127659933
291.6666666666667


In [30]:
# Structured arrays - mentioning compound datatypes.
# matrix multiplication and outer product
x=np.random.randint(10, size=(2,2))
y=np.random.randint(10, size=(2,2))
print(x)
print(y)
# print(np.multiply(x,y))  # element wise multiplication
# print(np.matmul(x,y))
# print(np.dot(x,y))  # dot product of vectors as well as matrix multiplication.
print(np.multiply.outer(x,y))

[[6 6]
 [7 6]]
[[2 1]
 [3 7]]
[[[[12  6]
   [18 42]]

  [[12  6]
   [18 42]]]


 [[[14  7]
   [21 49]]

  [[12  6]
   [18 42]]]]
