In [2]:
import pandas as pd
import numpy as np

In [16]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n:])
    return ret[n - 1:] / n

In [17]:
a=np.arange(10)
print(moving_average(a, n=4))

[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
[10. 14. 18. 22. 26. 30.]
[1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [8]:
# Creating pandas series using existing values.
# Attributes: values, index
data = pd.Series([10,20,30,40,50,60,70], index=['a',3,'b',4,5,'c',11])
data.index
# pd.rolling_mean(data,3)
# moving_average(data)

Index(['a', 3, 'b', 4, 5, 'c', 11], dtype='object')

In [9]:
data.values

array([10, 20, 30, 40, 50, 60, 70])

In [29]:
data=pd.Series([10,20,303,404,5,595])
data

0     10
1     20
2    303
3    404
4      5
5    595
dtype: int64

In [16]:
# Accessing the elements through index
data[3:]

4     40
5     50
c     60
11    70
dtype: int64

In [36]:
# Creating Series through explicit index, non-sequential and mixed indices.
age = pd.Series([25,20,30,40,56, 35], index=["ram","shiva","kumar","raj","ravi", "vamsi"])
age
qual = pd.Series(["BTech","MTech", "MCA", "BTech", "PHD","MBA"], index=["ram","shiva","kumar","raj","ravi", "vamsi"])
qual
email = pd.Series(["ram@gmail.com", "shiva@gmail.com", "kumar@gmail.com", "raj@gmail.com","ravi@gmail.com", "vamsi@gmail.com"]
                 , index=["ram","shiva","kumar","raj","ravi", "vamsi"])
email

emp_data = pd.DataFrame({'age':age, 'qual':qual, 'mailid':email})
emp_data

age   qual           mailid
ram     25  BTech    ram@gmail.com
shiva   20  MTech  shiva@gmail.com
kumar   30    MCA  kumar@gmail.com
raj     40  BTech    raj@gmail.com
ravi    56    PHD   ravi@gmail.com
vamsi   35    MBA  vamsi@gmail.com

In [63]:
# Creating series from dictionary.
age = pd.Series({"ram":25,"shiva":20,"kumar":30,"raj":40,
                 "ravi":56, "vamsi":35})
age
qual = pd.Series({"ram":"BTech","shiva":"MTech","kumar":"MCA",
                  "raj":"BTech","ravi":"PHD", "vamsi":"MBA"})
qual
email = pd.Series({"ram":"ram@gmail.com", "shiva":"shiva@gmail.com", 
                   "kumar":"kumar@gmail.com", "raj":"raj@gmail.com",
                   "ravi":"ravi@gmail.com", "vamsi":"vamsi@gmail.com"})
email
emp_data = pd.DataFrame({'age':age, 'qual':qual, 'mailid':email})
emp_data["age"]
emp_data.columns
print(emp_data)
emp_data.describe()

       age   qual           mailid
ram     25  BTech    ram@gmail.com
shiva   20  MTech  shiva@gmail.com
kumar   30    MCA  kumar@gmail.com
raj     40  BTech    raj@gmail.com
ravi    56    PHD   ravi@gmail.com
vamsi   35    MBA  vamsi@gmail.com


age
count   6.000000
mean   34.333333
std    12.754084
min    20.000000
25%    26.250000
50%    32.500000
75%    38.750000
max    56.000000

In [5]:
emp_ge = pd.DataFrame(age, columns=['age'])
emp_ge

age
ram     25
shiva   20
kumar   30
raj     40
ravi    56
vamsi   35

In [53]:
dummy1 = pd.DataFrame([{'a':10, 'b':20, 'c':20},{'b':10,'c':100, 'd':200},{'a':100, 'b':200,'c':200, 'd':34}])
dummy1

a    b    c      d
0   10.0   20   20    NaN
1    NaN   10  100  200.0
2  100.0  200  200   34.0

In [59]:
dummy = pd.DataFrame(np.random.randint(30,40, size=(5,4)), columns=['temp','wind','c', 'd'])
# dummy.iloc[:3, :2]
print(dummy)
print(dummy['temp'].min())
# dummy.add(dummy1, fill_value=10)
dummy.describe()

   temp  wind   c   d
0    30    34  38  34
1    37    39  38  39
2    36    36  38  32
3    36    39  32  39
4    36    39  37  33
30


temp       wind          c          d
count   5.000000   5.000000   5.000000   5.000000
mean   35.000000  37.400000  36.600000  35.400000
std     2.828427   2.302173   2.607681   3.361547
min    30.000000  34.000000  32.000000  32.000000
25%    36.000000  36.000000  37.000000  33.000000
50%    36.000000  39.000000  38.000000  34.000000
75%    36.000000  39.000000  38.000000  39.000000
max    37.000000  39.000000  38.000000  39.000000

In [18]:
bank_data=pd.read_excel('/home/shiva/Downloads/contactdetails.xls')
bank_data.head()
# tail()

Sr No       Bank Name                Bank Official Name  \
0    NaN             NaN                               NaN   
1    1.0  Allahabad Bank             Mr.Pankaj Tripathi      
2    NaN             NaN                Mr.Rajaram K         
3    NaN             NaN         Mr.Asish Ranjan Mahana      
4    NaN             NaN  Office Land line numbers & email   

            Contact Number                     E-mail ID  
0                      NaN                           NaN  
1               9969602752    pankaj@allahabadbank.co.in  
2             9987672771     rajaram@allahabadbank.co.in  
3               9969630749  mahana_a@allahabadbank.co.in  
4  (022) 2783 6061 - 6065                            NaN

In [19]:
bank_data.set_index(['Sr No']).head()

Bank Name                Bank Official Name  \
Sr No                                                     
NaN               NaN                               NaN   
1.0    Allahabad Bank             Mr.Pankaj Tripathi      
NaN               NaN                Mr.Rajaram K         
NaN               NaN         Mr.Asish Ranjan Mahana      
NaN               NaN  Office Land line numbers & email   

                Contact Number                     E-mail ID  
Sr No                                                         
NaN                        NaN                           NaN  
1.0                 9969602752    pankaj@allahabadbank.co.in  
NaN               9987672771     rajaram@allahabadbank.co.in  
NaN                 9969630749  mahana_a@allahabadbank.co.in  
NaN    (022) 2783 6061 - 6065                            NaN

In [20]:
# bank_data.isnull()
s = pd.Series([1,None, 'hello'])
s[s.notnull()]
# bank_data.dropna() # removes the rows having atleast one row.
# bank_data.dropna(thresh=2, axis='columns').head() # check for atleast 2 valid entries.
bank_data=bank_data.dropna(how='all')  # if all the elements of a row is Nan, then remove that row

In [46]:
bank_data.head()

Sr No       Bank Name                Bank Official Name  \
1    1.0  Allahabad Bank             Mr.Pankaj Tripathi      
2    NaN             NaN                Mr.Rajaram K         
3    NaN             NaN         Mr.Asish Ranjan Mahana      
4    NaN             NaN  Office Land line numbers & email   
5    NaN             NaN                               NaN   

                                Contact Number                     E-mail ID  
1                                   9969602752    pankaj@allahabadbank.co.in  
2                                 9987672771     rajaram@allahabadbank.co.in  
3                                   9969630749  mahana_a@allahabadbank.co.in  
4                      (022) 2783 6061 - 6065                            NaN  
5  (022) 2784 1183 - 1185 [Ext. No. 503 & 504]   cbscell@allahabadbank.co.in

In [22]:
# bank_data.fillna(10) # fill with 10 for all Nan values
x=bank_data.fillna(method='ffill')
x.head(10)
# print(x.columns)
x.to_csv("sample.csv", index=False, columns=["Bank Name", "Bank Official Name"])

Sr No       Bank Name                Bank Official Name  \
1     1.0  Allahabad Bank             Mr.Pankaj Tripathi      
2     1.0  Allahabad Bank                Mr.Rajaram K         
3     1.0  Allahabad Bank         Mr.Asish Ranjan Mahana      
4     1.0  Allahabad Bank  Office Land line numbers & email   
5     1.0  Allahabad Bank  Office Land line numbers & email   
7     2.0     Andhra Bank           Andhra Bank Call Center   
8     2.0     Andhra Bank           Andhra Bank Call Center   
11    3.0       Axis Bank                    Mr.Arun Haldar   
12    3.0       Axis Bank                    Mr.Arun Haldar   
14    4.0  Bank of Baroda                 Mr.Mithil K Mehta   

                                 Contact Number  \
1                                    9969602752   
2                                  9987672771     
3                                    9969630749   
4                       (022) 2783 6061 - 6065    
5   (022) 2784 1183 - 1185 [Ext. No. 503 & 504]   
7                                 1800 425 1515   
8                                 1800 425 1515   
11             033- 2430 8221/ 8217/ 8225/ 8213   
12                              Mob: 9830378877   
14                                 0265-2225209   

                          E-mail ID  
1        pankaj@allahabadbank.co.in  
2       rajaram@allahabadbank.co.in  
3      mahana_a@allahabadbank.co.in  
4      mahana_a@allahabadbank.co.in  
5       cbscell@allahabadbank.co.in  
7          cbs-gbm@andhrabank.co.in  
8   cbs-interfaces@andhrabank.co.in  
11       epayment.help@axisbank.com  
12       epayment.help@axisbank.com  
14         etax.ho@bankofbaroda.com

In [50]:
bank_data.head()

Sr No       Bank Name                Bank Official Name  \
1    1.0  Allahabad Bank             Mr.Pankaj Tripathi      
2    NaN             NaN                Mr.Rajaram K         
3    NaN             NaN         Mr.Asish Ranjan Mahana      
4    NaN             NaN  Office Land line numbers & email   
5    NaN             NaN                               NaN   

                                Contact Number                     E-mail ID  
1                                   9969602752    pankaj@allahabadbank.co.in  
2                                 9987672771     rajaram@allahabadbank.co.in  
3                                   9969630749  mahana_a@allahabadbank.co.in  
4                      (022) 2783 6061 - 6065                            NaN  
5  (022) 2784 1183 - 1185 [Ext. No. 503 & 504]   cbscell@allahabadbank.co.in